---
- name: Configuring the Nomad in /etc/hosts [Linux]
  blockinfile:
    block: |
      {{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  become: true
  with_items:
    - "{{ groups['nomad'] }}"

- name: Setting up hostname of Nomad nodes [Linux]
  hostname:
    name: "{{ inventory_hostname }}"
  become: true
